//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.20 at 09:46:28 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.springframework.org/test", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.springframework.batch.item.jaxb;
